CREATE TABLE customer_tb (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zip_code VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   CONSTRAINT pk_customer_tb PRIMARY KEY (id)
);

ALTER TABLE customer_tb ADD CONSTRAINT uc_customer_tb_cpf UNIQUE (cpf);

ALTER TABLE customer_tb ADD CONSTRAINT uc_customer_tb_email UNIQUE (email);