CREATE TABLE credit_tb (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   credit_code UUID NOT NULL,
   credit_value DECIMAL NOT NULL,
   day_first_intallment date NOT NULL,
   number_of_installment INT NOT NULL,
   status VARCHAR(255),
   customer_id BIGINT,
   CONSTRAINT pk_credit_tb PRIMARY KEY (id)
);

ALTER TABLE credit_tb ADD CONSTRAINT uc_credit_tb_creditcode UNIQUE (credit_code);

ALTER TABLE credit_tb ADD CONSTRAINT FK_CREDIT_TB_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer_tb (id);